/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypeSafetyRouteRouteImport } from './routes/type-safety.route'
import { Route as TelemetryRouteRouteImport } from './routes/telemetry.route'
import { Route as SqlHelpersRouteRouteImport } from './routes/sql-helpers.route'
import { Route as ServingRouteRouteImport } from './routes/serving.route'
import { Route as ReconnectRouteRouteImport } from './routes/reconnect.route'
import { Route as LakebaseRouteRouteImport } from './routes/lakebase.route'
import { Route as GenieRouteRouteImport } from './routes/genie.route'
import { Route as FilesRouteRouteImport } from './routes/files.route'
import { Route as DataVisualizationRouteRouteImport } from './routes/data-visualization.route'
import { Route as ChartInferenceRouteRouteImport } from './routes/chart-inference.route'
import { Route as ArrowAnalyticsRouteRouteImport } from './routes/arrow-analytics.route'
import { Route as AnalyticsRouteRouteImport } from './routes/analytics.route'
import { Route as IndexRouteImport } from './routes/index'

const TypeSafetyRouteRoute = TypeSafetyRouteRouteImport.update({
  id: '/type-safety',
  path: '/type-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRouteRoute = TelemetryRouteRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlHelpersRouteRoute = SqlHelpersRouteRouteImport.update({
  id: '/sql-helpers',
  path: '/sql-helpers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServingRouteRoute = ServingRouteRouteImport.update({
  id: '/serving',
  path: '/serving',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconnectRouteRoute = ReconnectRouteRouteImport.update({
  id: '/reconnect',
  path: '/reconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const LakebaseRouteRoute = LakebaseRouteRouteImport.update({
  id: '/lakebase',
  path: '/lakebase',
  getParentRoute: () => rootRouteImport,
} as any)
const GenieRouteRoute = GenieRouteRouteImport.update({
  id: '/genie',
  path: '/genie',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRouteRoute = FilesRouteRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DataVisualizationRouteRoute = DataVisualizationRouteRouteImport.update({
  id: '/data-visualization',
  path: '/data-visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartInferenceRouteRoute = ChartInferenceRouteRouteImport.update({
  id: '/chart-inference',
  path: '/chart-inference',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrowAnalyticsRouteRoute = ArrowAnalyticsRouteRouteImport.update({
  id: '/arrow-analytics',
  path: '/arrow-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRouteRoute = AnalyticsRouteRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteRoute
  '/arrow-analytics': typeof ArrowAnalyticsRouteRoute
  '/chart-inference': typeof ChartInferenceRouteRoute
  '/data-visualization': typeof DataVisualizationRouteRoute
  '/files': typeof FilesRouteRoute
  '/genie': typeof GenieRouteRoute
  '/lakebase': typeof LakebaseRouteRoute
  '/reconnect': typeof ReconnectRouteRoute
  '/serving': typeof ServingRouteRoute
  '/sql-helpers': typeof SqlHelpersRouteRoute
  '/telemetry': typeof TelemetryRouteRoute
  '/type-safety': typeof TypeSafetyRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteRoute
  '/arrow-analytics': typeof ArrowAnalyticsRouteRoute
  '/chart-inference': typeof ChartInferenceRouteRoute
  '/data-visualization': typeof DataVisualizationRouteRoute
  '/files': typeof FilesRouteRoute
  '/genie': typeof GenieRouteRoute
  '/lakebase': typeof LakebaseRouteRoute
  '/reconnect': typeof ReconnectRouteRoute
  '/serving': typeof ServingRouteRoute
  '/sql-helpers': typeof SqlHelpersRouteRoute
  '/telemetry': typeof TelemetryRouteRoute
  '/type-safety': typeof TypeSafetyRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteRoute
  '/arrow-analytics': typeof ArrowAnalyticsRouteRoute
  '/chart-inference': typeof ChartInferenceRouteRoute
  '/data-visualization': typeof DataVisualizationRouteRoute
  '/files': typeof FilesRouteRoute
  '/genie': typeof GenieRouteRoute
  '/lakebase': typeof LakebaseRouteRoute
  '/reconnect': typeof ReconnectRouteRoute
  '/serving': typeof ServingRouteRoute
  '/sql-helpers': typeof SqlHelpersRouteRoute
  '/telemetry': typeof TelemetryRouteRoute
  '/type-safety': typeof TypeSafetyRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/arrow-analytics'
    | '/chart-inference'
    | '/data-visualization'
    | '/files'
    | '/genie'
    | '/lakebase'
    | '/reconnect'
    | '/serving'
    | '/sql-helpers'
    | '/telemetry'
    | '/type-safety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/arrow-analytics'
    | '/chart-inference'
    | '/data-visualization'
    | '/files'
    | '/genie'
    | '/lakebase'
    | '/reconnect'
    | '/serving'
    | '/sql-helpers'
    | '/telemetry'
    | '/type-safety'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/arrow-analytics'
    | '/chart-inference'
    | '/data-visualization'
    | '/files'
    | '/genie'
    | '/lakebase'
    | '/reconnect'
    | '/serving'
    | '/sql-helpers'
    | '/telemetry'
    | '/type-safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRouteRoute: typeof AnalyticsRouteRoute
  ArrowAnalyticsRouteRoute: typeof ArrowAnalyticsRouteRoute
  ChartInferenceRouteRoute: typeof ChartInferenceRouteRoute
  DataVisualizationRouteRoute: typeof DataVisualizationRouteRoute
  FilesRouteRoute: typeof FilesRouteRoute
  GenieRouteRoute: typeof GenieRouteRoute
  LakebaseRouteRoute: typeof LakebaseRouteRoute
  ReconnectRouteRoute: typeof ReconnectRouteRoute
  ServingRouteRoute: typeof ServingRouteRoute
  SqlHelpersRouteRoute: typeof SqlHelpersRouteRoute
  TelemetryRouteRoute: typeof TelemetryRouteRoute
  TypeSafetyRouteRoute: typeof TypeSafetyRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/type-safety': {
      id: '/type-safety'
      path: '/type-safety'
      fullPath: '/type-safety'
      preLoaderRoute: typeof TypeSafetyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-helpers': {
      id: '/sql-helpers'
      path: '/sql-helpers'
      fullPath: '/sql-helpers'
      preLoaderRoute: typeof SqlHelpersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serving': {
      id: '/serving'
      path: '/serving'
      fullPath: '/serving'
      preLoaderRoute: typeof ServingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconnect': {
      id: '/reconnect'
      path: '/reconnect'
      fullPath: '/reconnect'
      preLoaderRoute: typeof ReconnectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lakebase': {
      id: '/lakebase'
      path: '/lakebase'
      fullPath: '/lakebase'
      preLoaderRoute: typeof LakebaseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genie': {
      id: '/genie'
      path: '/genie'
      fullPath: '/genie'
      preLoaderRoute: typeof GenieRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-visualization': {
      id: '/data-visualization'
      path: '/data-visualization'
      fullPath: '/data-visualization'
      preLoaderRoute: typeof DataVisualizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-inference': {
      id: '/chart-inference'
      path: '/chart-inference'
      fullPath: '/chart-inference'
      preLoaderRoute: typeof ChartInferenceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrow-analytics': {
      id: '/arrow-analytics'
      path: '/arrow-analytics'
      fullPath: '/arrow-analytics'
      preLoaderRoute: typeof ArrowAnalyticsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRouteRoute: AnalyticsRouteRoute,
  ArrowAnalyticsRouteRoute: ArrowAnalyticsRouteRoute,
  ChartInferenceRouteRoute: ChartInferenceRouteRoute,
  DataVisualizationRouteRoute: DataVisualizationRouteRoute,
  FilesRouteRoute: FilesRouteRoute,
  GenieRouteRoute: GenieRouteRoute,
  LakebaseRouteRoute: LakebaseRouteRoute,
  ReconnectRouteRoute: ReconnectRouteRoute,
  ServingRouteRoute: ServingRouteRoute,
  SqlHelpersRouteRoute: SqlHelpersRouteRoute,
  TelemetryRouteRoute: TelemetryRouteRoute,
  TypeSafetyRouteRoute: TypeSafetyRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
