import fs from "node:fs/promises";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { generateServingTypes } from "../generator";

vi.mock("node:fs/promises");

// Mock cache module
vi.mock("../cache", () => ({
  CACHE_VERSION: "1",
  hashSchema: vi.fn(() => "mock-hash"),
  loadServingCache: vi.fn(async () => ({ version: "1", endpoints: {} })),
  saveServingCache: vi.fn(async () => {}),
}));

// Mock fetcher
const mockFetchOpenApiSchema = vi.fn();
vi.mock("../fetcher", () => ({
  fetchOpenApiSchema: (...args: any[]) => mockFetchOpenApiSchema(...args),
}));

// Mock WorkspaceClient
vi.mock("@databricks/sdk-experimental", () => ({
  WorkspaceClient: vi.fn(() => ({ config: {} })),
}));

const CHAT_OPENAPI_SPEC = {
  openapi: "3.1.0",
  info: { title: "test", version: "1" },
  paths: {
    "/served-models/llm/invocations": {
      post: {
        requestBody: {
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  messages: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        role: { type: "string" },
                        content: { type: "string" },
                      },
                    },
                  },
                  temperature: { type: "number", nullable: true },
                  stream: { type: "boolean", nullable: true },
                },
              },
            },
          },
        },
        responses: {
          "200": {
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    model: { type: "string" },
                    choices: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          message: {
                            type: "object",
                            properties: {
                              role: { type: "string" },
                              content: { type: "string" },
                            },
                          },
                          finish_reason: { type: "string" },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
};

describe("generateServingTypes", () => {
  const outFile = "/tmp/test-serving-types.d.ts";

  beforeEach(() => {
    vi.mocked(fs.writeFile).mockResolvedValue();
    process.env.TEST_SERVING_ENDPOINT = "my-endpoint";
  });

  afterEach(() => {
    delete process.env.TEST_SERVING_ENDPOINT;
    delete process.env.DATABRICKS_SERVING_ENDPOINT;
    vi.restoreAllMocks();
  });

  test("generates .d.ts with module augmentation for a chat endpoint", async () => {
    mockFetchOpenApiSchema.mockResolvedValue({
      spec: CHAT_OPENAPI_SPEC,
      pathKey: "/served-models/llm/invocations",
    });

    await generateServingTypes({
      outFile,
      endpoints: { llm: { env: "TEST_SERVING_ENDPOINT" } },
      noCache: true,
    });

    expect(fs.writeFile).toHaveBeenCalledWith(
      outFile,
      expect.any(String),
      "utf-8",
    );
    const output = vi.mocked(fs.writeFile).mock.calls[0][1] as string;

    // Verify module augmentation structure
    expect(output).toContain("// Auto-generated by AppKit - DO NOT EDIT");
    expect(output).toContain('import "@databricks/appkit"');
    expect(output).toContain('import "@databricks/appkit-ui/react"');
    expect(output).toContain('declare module "@databricks/appkit"');
    expect(output).toContain('declare module "@databricks/appkit-ui/react"');
    expect(output).toContain("interface ServingEndpointRegistry");
    expect(output).toContain("llm:");
    expect(output).toContain("request:");
    expect(output).toContain("response:");
    expect(output).toContain("chunk:");
  });

  test("strips stream property from generated request type", async () => {
    mockFetchOpenApiSchema.mockResolvedValue({
      spec: CHAT_OPENAPI_SPEC,
      pathKey: "/served-models/llm/invocations",
    });

    await generateServingTypes({
      outFile,
      endpoints: { llm: { env: "TEST_SERVING_ENDPOINT" } },
      noCache: true,
    });

    const output = vi.mocked(fs.writeFile).mock.calls[0][1] as string;
    // `stream` should be stripped from request type
    expect(output).toContain("messages");
    expect(output).toContain("temperature");
    expect(output).not.toMatch(/\bstream\??\s*:/);
  });

  test("emits generic types when env var is not set", async () => {
    delete process.env.TEST_SERVING_ENDPOINT;

    await generateServingTypes({
      outFile,
      endpoints: { llm: { env: "TEST_SERVING_ENDPOINT" } },
      noCache: true,
    });

    expect(mockFetchOpenApiSchema).not.toHaveBeenCalled();
    const output = vi.mocked(fs.writeFile).mock.calls[0][1] as string;
    expect(output).toContain("llm:");
    expect(output).toContain("Record<string, unknown>");
  });

  test("skips generation when no endpoints configured and no env var", async () => {
    await generateServingTypes({
      outFile,
      noCache: true,
    });

    expect(mockFetchOpenApiSchema).not.toHaveBeenCalled();
    expect(fs.writeFile).not.toHaveBeenCalled();
  });

  test("emits generic types when schema fetch returns null", async () => {
    mockFetchOpenApiSchema.mockResolvedValue(null);

    await generateServingTypes({
      outFile,
      endpoints: { llm: { env: "TEST_SERVING_ENDPOINT" } },
      noCache: true,
    });

    const output = vi.mocked(fs.writeFile).mock.calls[0][1] as string;
    expect(output).toContain("llm:");
    expect(output).toContain("Record<string, unknown>");
  });

  test("resolves default endpoint from DATABRICKS_SERVING_ENDPOINT", async () => {
    process.env.DATABRICKS_SERVING_ENDPOINT = "my-default-endpoint";
    mockFetchOpenApiSchema.mockResolvedValue({
      spec: CHAT_OPENAPI_SPEC,
      pathKey: "/served-models/llm/invocations",
    });

    await generateServingTypes({
      outFile,
      noCache: true,
    });

    expect(mockFetchOpenApiSchema).toHaveBeenCalledWith(
      expect.anything(),
      "my-default-endpoint",
      undefined,
    );

    const output = vi.mocked(fs.writeFile).mock.calls[0][1] as string;
    expect(output).toContain("default:");
  });
});
